### ISSUE TITLE
Does not work with the Fish shell.

### ISSUE THREAD

**Issue by eternauta1337** [nvllsvm/base16-shell-preview#3]
Error:

color21 ~/.config/base16-shell/scripts/base16-atelier-heath-light.sh (line 43): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
                                                                                                                                                                                         put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }
                                                                 ^
                                                                  <W> fish: Error while reading file /home/bob/.config/base16-shell/scripts/base16-atelier-heath-light.sh

**Comment by combro2k** [comment]
Quick fix for fish shell:

env SHELL=/bin/sh base16-shell-preview

**Comment by andrewrabert** [comment]
Should be fixed in 0.4.0.

**Comment by combro2k** [comment]
Not totally..
it seems bash use *base16_* prefix while the fish one use the *base16-* prefix.
a little design flaw I think.
what we can do is code something like USER_SHELL.endswith('fish') or so?

**Comment by combro2k** [comment]
There are some more issues  with it it seems;
If I edit the code and 'fix' the base16_ to base16- the shell is being somehow replaced
so if I press enter the shell exists. Don't know why yet, however if I replace subprocess.Popen by subprocess.run it works flawlessly but you lose support for Python 2.7 afaik.

**Comment by andrewrabert** [comment]
@combro2k I've replaced the alias execution in favor of symlinking theme directly in Python. Does it work in your fish setup?
https://github.com/nvllsvm/base16-shell-preview/commit/8f389bc8ce050a26bdf0143dde53d3739ef8f88d

Any additional logic one wishes to run upon theme change should be setup stored in the path of env var `BASE16_SHELL_HOOKS`. This is the existing behavior of the shell helper script, but no the fish helper.

https://github.com/nvllsvm/base16-shell-preview/commit/02556335dc278a497cdac1c47796c730c22fa7ec

**Comment by combro2k** [comment]
Let me have a check, will come back to you :-)

**Comment by combro2k** [comment]
I see...
Don't know yet how this hooks work, how is it exactly implemented?
I will fork the base16-shell repo and fix that behavior :-) it *should* be the same for both shells

**Comment by combro2k** [comment]
The symlinking works, only miss the ~/.vim_background update.
But I guess I can fix that, the hooks has a small issue now cause the BASE16_THEME variable is not set now :-) so you don't have that variable available in the hook script.

**Comment by combro2k** [comment]
Did a pull request to fix the issues with BASE16_THEME which was not set on the scripts anyway for fish ..
Fish a little different as 'normal' shell unfortunately and a lot of people aren't using it because of that.
But that being said, I hope Chris will merge my pull request, we will see if it does or not ;-)

https://github.com/chriskempson/base16-shell/pull/175

**Comment by andrewrabert** [comment]
I purposefully excluded the `.vim_background` logic as it's too opinionated. Just use a hook.

----

Be aware that `BASE16_THEME` is not consistent. The initial shell load of a theme results in the full theme name (ex.`BASE16_THEME=base16-bright`) while the aliases exclude the prefix (ex. `BASE16_THEME=bright`).

This doesn't matter too much since the hooks are only ever run from the alias.

https://github.com/chriskempson/base16-shell/pull/147

Anyway - I've updated base16-shell-preview to set `BASE16_THEME` when executing the hooks. The value of the variable is consistent with the alias (`BASE16_THEME=bright`).
https://github.com/nvllsvm/base16-shell-preview/commit/081d285cf68a9f0628b15dcc0b5774a70ec8345e

**Comment by andrewrabert** [comment]
Released version 0.5.0

**Comment by combro2k** [comment]
Thank you, clear enough ;-)
Thanks for fixing it
